USE [master]
GO

/****** Object:  Database [MoneyAppplication]    Script Date: 01/10/2020 10:47:17 ******/
CREATE DATABASE [MoneyAppplication]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MoneyAppplication', FILENAME = N'C:\Users\okudo\MoneyAppplication.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MoneyAppplication_log', FILENAME = N'C:\Users\okudo\MoneyAppplication_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [MoneyAppplication] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MoneyAppplication].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MoneyAppplication] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MoneyAppplication] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MoneyAppplication] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MoneyAppplication] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MoneyAppplication] SET ARITHABORT OFF 
GO

ALTER DATABASE [MoneyAppplication] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [MoneyAppplication] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MoneyAppplication] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MoneyAppplication] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MoneyAppplication] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MoneyAppplication] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MoneyAppplication] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MoneyAppplication] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MoneyAppplication] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MoneyAppplication] SET  ENABLE_BROKER 
GO

ALTER DATABASE [MoneyAppplication] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MoneyAppplication] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MoneyAppplication] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MoneyAppplication] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MoneyAppplication] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MoneyAppplication] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [MoneyAppplication] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MoneyAppplication] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MoneyAppplication] SET  MULTI_USER 
GO

ALTER DATABASE [MoneyAppplication] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MoneyAppplication] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MoneyAppplication] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MoneyAppplication] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MoneyAppplication] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MoneyAppplication] SET QUERY_STORE = OFF
GO

USE [MoneyAppplication]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [MoneyAppplication] SET  READ_WRITE 
GO

